-- This legacy SQL file is kept for reference only.
-- It targets MySQL/XAMPP and is not portable to PostgreSQL.
-- Use the Laravel migrations in backend/database/migrations/ instead:
--
--   php artisan migrate
--
-- The schema is now maintained through framework migrations so the project
-- can run on both MySQL and PostgreSQL.
